on: [push]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [arm-unknown-linux-gnueabihf, armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }}
      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name="dorsum"

          dirname="$binary_name-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/debug/$binary_name" "$dirname"

          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: dorsum_${{ matrix.target }}
          path: ${{ env.ASSET }}